icon thing
scratchaddons-community/scradd pull request #430
Opened 2023-11-12 15:14 UTC by callumjt

does that thing that #429 wants

2023-11-12 15:29 UTC, RedGuy12 commented
its aupposed to be modules/settings.ts

2023-11-12 15:29 UTC, RedGuy12 commented
also "resolves #429"

2023-11-12 15:47 UTC, callumjt commented
> its aupposed to be modules/settings.ts

thats where i put it in

2023-11-12 15:48 UTC, callumjt commented
> > its aupposed to be modules/settings.ts
> 
> thats where i put it in

oh wait, i uploaded to wrong place

2023-11-12 21:53 UTC, RedGuy12 commented on modules/settings.ts
> +	const member = (await guild.members.fetch(id).catch(() => void 0)) as GuildMember;
don't cast :sob: just use optional chaining???

2023-11-12 21:54 UTC, RedGuy12 commented on modules/settings.ts
> +		: `${userMention(id)} ${icon} `;
there should not be a trailing space

2023-11-12 21:54 UTC, RedGuy12 requested changes

2023-11-12 21:54 UTC, RedGuy12 commented on modules/settings.ts
> +	if (useMentions) return icon + userMention(id);
the ping should go first, then a space, then the emoji

2023-11-12 21:57 UTC, callumjt commented on modules/settings.ts
> +	const member = (await guild.members.fetch(id).catch(() => void 0)) as GuildMember;
Wha

2023-11-12 21:58 UTC, callumjt commented on modules/settings.ts
> +		: `${userMention(id)} ${icon} `;
Uhh how did that get in there

2023-11-12 22:04 UTC, RedGuy12 commented on modules/settings.ts
> +	const member = (await guild.members.fetch(id).catch(() => void 0)) as GuildMember;
![image](https://github.com/scratchaddons-community/scradd/assets/61329810/7402c096-7af6-497a-806b-5cd40768cfb9)
![image](https://github.com/scratchaddons-community/scradd/assets/61329810/ac8bcdd8-5bdf-4642-94c6-8e4ed36b679a)

2023-11-21 15:47 UTC, callumjt commented
@RedGuy12 I'm assuming this won't be merged until you find a way to handle custom icons?

2023-11-21 16:34 UTC, callumjt commented
Could just detect if it's not Unicode emoji and if it isn't display mod badge instead since only mods have custom icons?

2023-11-21 16:36 UTC, RedGuy12 commented
that's not a correct statement

2023-11-21 16:50 UTC, callumjt commented
> that's not a correct statement

Elaborate?

2023-11-22 23:16 UTC, RedGuy12 commented
> > that's not a correct statement
> 
> Elaborate?

for example: active booster, sa dev

2023-11-23 07:57 UTC, callumjt commented
> > > that's not a correct statement
> > 
> > 
> > Elaborate?
> 
> for example: active booster, sa dev

I thought boosters don’t get icons?

2023-11-23 14:01 UTC, RedGuy12 commented
those two roles, among others, have role icons

2023-11-23 14:01 UTC, RedGuy12 commented
those two roles, among others, have role icons

2023-12-16 03:32 UTC, RedGuy12 commented
@dependabot rebase

2024-01-10 02:33 UTC, closed without merging